### ISSUE TITLE
Support Expr.ValueWithName expressions in decompile?

### ISSUE THREAD

**Issue by eiriktsarpalis** [SwensenSoftware/unquote#133]
Would you be willing to add support for Expr.ValueWithName expressions in the `decompile` method? I could provide a PR

**Comment by stephen-swensen** [comment]
Circling back to this issue, I've got an implementation [here ](https://github.com/SwensenSoftware/unquote/pull/146/commits/ea9befa87b25ee43db33d2503f09f7bf5b8112cd)as part of a [bigger PR](https://github.com/SwensenSoftware/unquote/pull/146).

@eiriktsarpalis thank you for creating this issue and for the original PR you provided. I'll follow-up more on that PR, but long story short:

- the implementation I linked above ended up being more complicated than just decompiling `ValueWithName` expressions because we also needed to implement `ValueWithName` reduction to `Value` AND it turns out `ValueWithName` has some quirks around it having to do with the fact that F# team wanted it to be generally interchangeable with `Value` expressions.
- the PR you provided had a larger, arguably separate, discussion around providing a less verbose assertion operator. I've spun that off into a new issue: https://github.com/SwensenSoftware/unquote/issues/148
